version: "3"
services:
  
################## MOSQUITTO #################################
  mosquitto:
    # de donde se va a tomar el dockerfile
    container_name: mosquitto
    image: eclipse-mosquitto:1.6.9@sha256:88b43f5ea09ebf443dc66bdd675f5c84dbf6fcd6b7028dbc1873ec66d894c89c
    ports:
      - 1883:1883
    volumes:
      - /home/pi/docker/mosquitto/config:/mosquitto/config
      - /home/pi/docker/mosquitto/data:/mosquitto/data
      - /home/pi/docker/mosquitto/log:/mosquitto/log
    #va a reiniciar al menos que se pare a mano
    restart: unless-stopped




 ######################### PIHOLE ############################## 
  pihole:
    container_name: pihole
    #build: .
    image: pihole/pihole:beta-v5.0-armhf
    ports: 
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 80:80/tcp
      - 443:443/tcp

    environment:
      TZ: America/Cordoba
      WEBPASSWORD: 'cerro1870'
    # Volumes store your data between container upgrades
    volumes:
       - /home/pi/docker/pihole/etc-pihole/:/etc/pihole/
       - /home/pi/docker/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 1.1.1.1
      # Recommended but not required (DHCP needs NET_ADMIN)
      #  https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped


  ######################### NGINX ############################## 
  nginx:
    container_name: nginx
    image: nginx:1.17.9-alpine@sha256:b9ab338c9098779181906dc8b1862b7b97dce90d0ecf03063f3c9bf055ce0aff
    volumes:
      - /home/pi/docker/nginx/html:/usr/share/nginx/html
      # en la linea anterior se ponel el archivo index.html
      - /home/pi/docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf 
      # en la linea anterior le dice que puerto escuchar a nginx, ojo cuando tenenmos \
      # un servicio en el mismo puerto 80 por ejemplo pihole
    ports:
      - 81:81
    restart: unless-stopped


  ######################### PYTHON ############################## 
  python:
    container_name: python
    image: python:3.6.10-alpine3.11@sha256:587d59ecf83a8ba72531ac64032c2d72ff6f3e64205c287f835dda2f48da4b2d
